#Workaround for fan speed on appdaemon dashboard
#Set value of input select when fan speed changed on switch
- alias: Set Master Bedroom Ceiling Fan Speed Selector
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: fan.master_bedroom_ceiling_fan_level
  action:
     service: input_select.select_option
     data_template:
       entity_id: input_select.master_bedroom_ceiling_fan_speed
       option: '{{ states.fan.master_bedroom_ceiling_fan_level.attributes.speed }}'

#Workaround for fan speed on appdaemon dashboard
#Set fan speed when input changed
- alias: Set Master Bedroom Ceiling Fan Speed
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_select.master_bedroom_ceiling_fan_speed
  action:
     service: fan.set_speed
     entity_id: fan.master_bedroom_ceiling_fan_level
     data_template:
       speed: '{{ states.input_select.master_bedroom_ceiling_fan_speed.state }}'

- alias: "Set dark theme for the night"
  initial_state: on
  trigger:
    - platform: time
      at: '21:00'
  action:
    - service: frontend.set_theme
      data:
        name: midnight-remake

- alias: "Set light theme for day"
  initial_state: on
  trigger:
    - platform: time
      at: '9:00'
  action:
    - service: frontend.set_theme
      data:
        name: default

- alias: "Package Delivered"
  initial_state: on
  trigger:
    platform: state
    entity_id: sensor.deliveries_today
  action:
    - service: notify.pushover
      data_template:
        message: >
          Package delivered...

- alias: "Front Door Open Length"
  initial_state: on
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.front_door
    for:
      minutes: 1
  action:
    - service: notify.pushover
      data_template:
        message: >
          The front door has been opened for 1 minute..

- alias: "Back Door Open Length"
  initial_state: on
  trigger:
    platform: state
    to: 'on'
    entity_id: binary_sensor.back_door
    for:
      minutes: 1
  action:
    - service: notify.pushover
      data_template:
        message: >
          The back door has been opened for 1 minute..

#Switch
- alias: "Arlo Arm"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.arlo_status
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.security_camera_automation
    state: 'on'
  action:
    service: script.turn_on
    entity_id: script.arlo_arm

#Switch
- alias: "Arlo Disarm"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: input_boolean.arlo_status
    from: 'on'
    to: 'off'
  condition:
    condition: state
    entity_id: input_boolean.security_camera_automation
    state: 'on'
  action:
    service: script.turn_on
    entity_id: script.arlo_disarm

- alias: "Turn off House"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.trackers
    to: not_home
    for:
      seconds: 5
  action:
    service: homeassistant.turn_on
    entity_id: script.home_empty

- alias: "Arrived at Home"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.trackers
    to: home
  action:
    service: homeassistant.turn_on
    entity_id: script.home_occupied

- alias: "Turn on lamps when we get home"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: group.trackers
    from: not_home
    to: home
  condition:
    condition: sun
    after: sunset
    after_offset: "-00:30:00"
  action:
    service: homeassistant.turn_on
    entity_id: group.master_bedroom_lamps

- alias: "Button Press On!"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.office_toggle_switch
    to: "true"
  action:
    service: homeassistant.turn_on
    entity_id: group.andrew_desk

- alias: "Button Press Off!"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.office_toggle_switch
    to: "false"
  action:
    service: homeassistant.turn_off
    entity_id: group.andrew_desk

- alias: "Mount /Plex"
  initial_state: on
  trigger:
    platform: state
    entity_id: switch.nas
    from: 'off'
    to: 'on'
    for:
      seconds: 60
  action:
    service: shell_command.mount_plex

- alias: "Unmount /Plex"
  initial_state: on
  trigger:
    platform: state
    entity_id: switch.nas
    from: 'on'
    to: 'off'
    for:
      seconds: 120
  action:
    service: shell_command.umount_plex

#- id: ac_broken_cool
- alias: "Notify Andrew when AC BREAKS"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.thermostat_setpoint
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: climate.thermostat
        state: 'cool'
      - condition: numeric_state
        entity_id: sensor.thermostat_setpoint
        below: '68'
  action:
    - service: notify.pushover
      data_template:
        message: AC Broke.. Turning Off...
    - service: climate.set_operation_mode
      data:
        entity_id: climate.thermostat
        operation_mode: 'off'

#- id: ac_broken_heat
- alias: "Notify Andrew when AC BREAKS"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.thermostat_setpoint
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: climate.thermostat
        state: 'heat'
      - condition: numeric_state
        entity_id: sensor.thermostat_setpoint
        above: '72'
  action:
    - service: notify.pushover
      data_template:
        message: AC Broke.. Turning Off...
    - service: climate.set_operation_mode
      data:
        entity_id: climate.thermostat
        operation_mode: 'off'

#- id: ac_setpoint_change
- alias: "Notify Andrew when AC setpoint changes"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.thermostat_setpoint
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.ac_change_notification
        state: 'on'
      - condition: template
        value_template: '{{ trigger.entity_id != None }}'
      - condition: template
        value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  action:
    - service: notify.pushover
      data_template:
        message: >
          Setpoint Trigger: {{ trigger.to_state.state }}. Mode: {{ states.sensor.thermostat_operating_mode.state }}

#- id: ac_mode_change
- alias: "Notify Andrew when AC Mode changes"
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sensor.thermostat_operating_mode
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.ac_change_notification
        state: 'on'
      - condition: template
        value_template: '{{ trigger.entity_id != None }}'
      - condition: template
        value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'
  action:
    - service: notify.pushover
      data_template:
        message: >
          Mode Trigger: {{ states.sensor.thermostat_setpoint.state }}. Mode: {{ trigger.to_state.state }}

- alias: "Seventeentrack Update"
  initial_state: 'on'
  trigger:
    platform: event
    event_type: state_changed
  condition:
    condition: and
    conditions:
      - condition: template
        value_template: "{{ trigger.event.data.entity_id.startswith('sensor.seventeentrack_package_') }}"
      - condition: or
        conditions:
        - condition: template
          value_template: "{{ 'TX' in trigger.event.data.new_state.attributes.info_text }}"
        - condition: template
          value_template: "{{ 'Out for Delivery' in trigger.event.data.new_state.attributes.info_text }}"
        - condition: template
          value_template: "{{ 'Delivered' in trigger.event.data.new_state.attributes.info_text }}"
  action:
    service: notify.pushover
    data_template:
      message: >
        {{ trigger.event.data.new_state.attributes.friendly_name | replace("Seventeentrack Package: ","") }}: {{ trigger.event.data.new_state.attributes.info_text }}

- alias: "Bethany Commute"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: device_tracker.bethanys_iphone
    from: "Bethany Work"
  condition:
    condition: state
    entity_id: device_tracker.owntracks_android
    state: 'home'
  action:
    service: media_player.alexa_tts
    entity_id: media_player.andrews_kitchen_echo
    data:
      message: "Bethany is on her way home"

- alias: "Desk Drawer Open Toggle"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: binary_sensor.desk_keyboard_drawer
    from: 'off'
    to: 'on'
  action:
    service: homeassistant.toggle
    entity_id: group.andrew_desk


####################
# Mom and Dad Gate #
####################

- alias: "Webhook Trigger"
  initial_state: 'on'
  trigger:
    platform: webhook
    webhook_id: !secret gate_webhook_id
  action:
    service: script.turn_on
    entity_id: script.mom_and_dad_gate_toggle

- alias: "Mom and Dad Gate Notify Open"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.mom_and_dad_gate
    from: 'closed'
    to: 'open'
  action:
    - service: notify.pushover
      data_template:
        message: >
          Gate Opened

- alias: "Mom and Dad Gate Notify Closed"
  initial_state: 'on'
  trigger:
    platform: state
    entity_id: sensor.mom_and_dad_gate
    from: 'open'
    to: 'closed'
  action:
    - service: notify.pushover
      data_template:
        message: >
          Gate Closed

