# Describes the format for available services for the Solcast integration
update_forecasts:
  name: Update
  description: Fetches the forecasts from Solcast

force_update_forecasts:
  name: Force Update Forecasts
  description: Force fetches the forecasts from Solcast

force_update_estimates:
  name: Force Update Estimates
  description: Force fetches estimated actuals from Solcast

clear_all_solcast_data:
  name: Clear saved Solcast site data
  description: Deletes the solcast.json file to remove all current solcast site data

query_forecast_data:
  name: Query forecasts
  description: List of forecasts between start date/time and end date/time
  fields:
    start_date_time:
      example: "2024-10-06T00:00:00Z"
      selector:
        datetime:
    end_date_time:
      example: "2024-10-06T10:00:00Z"
      selector:
        datetime:
    undampened:
      example: "false"
    site:
      example: "1234-5678-9012-3456"

query_estimate_data:
  name: Query estimates
  description: List of estimated actuals between start date/time and end date/time
  fields:
    start_date_time:
      example: "2024-10-06T00:00:00Z"
      selector:
        datetime:
    end_date_time:
      example: "2024-10-06T10:00:00Z"
      selector:
        datetime:

set_dampening:
  name: Set forecasts dampening
  description: Set the hourly or half-hourly forecast dampening factors
  fields:
    damp_factor:
      example: "1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1"
    site:
      example: "1234-5678-9012-3456"

get_dampening:
  name: Get forecasts dampening
  description: Get the forecast dampening factors
  fields:
    site:
      example: "1234-5678-9012-3456"

set_hard_limit:
  name: Set inverter forecast hard limit in kW
  description: Prevent forecast values being higher than the inverter can produce
  fields:
    hard_limit:
      example: "6.0"

remove_hard_limit:
  name: Remove inverter forecast hard limit
  description: Remove set limit
